### ISSUE TITLE
Not (really) open source

### ISSUE THREAD

**Issue by indrora** [dfabulich/choicescript#109]
The license explicitly precludes commercial use, which goes against the OSI definitions of Open Source.

From the Opensource Initiative FAQ:

> **Can I call my program "Open Source" even if I don't use an approved license?**
>
>Please don't do that. If you call it "Open Source" without using an approved license, you will confuse people. This is not merely a theoretical concern — we have seen this confusion happen in the past, and it's part of the reason we have a formal license approval process. See also our page on license proliferation for why this is a problem.

Most notably, the [Annotated "OpenSource" definition](http://opensource.org/osd-annotated) has, most notably, a note that open source software may not restrict the endeavors of users of that software (point 1) and that you can't require a separate license for any use of the software (or derivatives, point 7).

Also, IANAL, but the license for a language only really applies for the language itself; Usages of the language are not considered coverable by licenses as they are a transformative act from one medium to another; in essence, closed-source software can be made with the GCC compiler, despite the GCC compiler being licensed under the GPL.

**Comment by indrora** [comment]
bump to see if this can get some traction.

**Comment by dfabulich** [comment]
We don't call ChoiceScript open source; we're aware that it doesn't satisfy OSI's definition. We may choose to adopt an open-source license at some point in the future, but there are no promises.
