### ISSUE TITLE
Can't set up and run in Mac

### ISSUE THREAD

**Issue by ungooglable** [dfabulich/choicescript#116]
When trying to open the Example Game in Safari I get following errors:

> #### JavaScript
> Couldn't load scenes/startup.txt
> The file is probably missing or empty.

and then

> #### JavaScript
> Couldn't load URL: scenes/startup.txt
> Error: NETWORK_ERR: XMLHttpRequest Exception 101

Then it shows 'Loading' progress bar but never loads

* Safari 6.2.8
* Mac OS X 10.8.5

----

#### PS

Also compile.html outputs following (inside the main browser window)

> EXPORT FAILED
> Error: Could not open web/mygame/index.html
> Your browser may not be supported. We recommend using Mozilla Firefox with compile.html.

**Comment by dfabulich** [comment]
We don't support Safari 6. It works fine in Safari 10 on macOS 10.12. If you can upgrade Safari, please do so; otherwise, try using Firefox instead.
